Repository katelyynn/bleh, pull requests merged in 2024-06, with the labels that each got.

#4 feat: profile notes
  fm/bleh.css
  fm/bleh.user.css
  fm/bleh.user.js
Labels: area:profiles, cute

#5 feat: style caching
  fm/bleh.user.js
Labels: area:style, cute

#3 feat: show guests as artist
  fm/bleh.css
  fm/bleh.user.css
  fm/bleh.user.js
Labels: area:guest-features, cute

#7 feat: artist scrobble milestone colours
  fm/bleh.css
  fm/bleh.user.css
  fm/bleh.user.js
Labels: cute, area:artist

#8 feat: artist corrections
  fm/bleh.user.js
Labels: cute, area:artist, area:track, area:album, system:corrections

#11 feat: redesign charts settings
  fm/bleh.css
  fm/bleh.user.css
  fm/bleh.user.js
Labels: cute, area:settings

#12 feat: redesign privacy tab
  fm/bleh.css
  fm/bleh.user.css
  fm/bleh.user.js
Labels: cute, area:settings

#13 feat: gallery bookmarks
  fm/bleh.css
  fm/bleh.user.css
  fm/bleh.user.js
Labels: cute, area:artist, area:gallery

#14 feat: polish translation
  fm/bleh.user.js
Labels: enhancement, area:translations

#15 fix: underscores splitting mentions
  fm/bleh.user.js
Labels: area:profiles, area:shoutbox

#17 feat: redesign
  fm/bleh.css
  fm/bleh.user.css
  fm/bleh.user.js
Labels: cute
