Repository katelyynn/bleh, pull requests merged in 2025-01, with the labels that each got.

#123 feat: 2025
  fm/bleh.css
  fm/bleh.user.css
  fm/bleh.user.js
  fm/changelog/2025.0113.md
  fm/changelog/changelog.json
  fm/changelog/img/badge.png
  fm/changelog/img/custom.png
  fm/changelog/img/evils.png
  fm/changelog/img/glow.png
  fm/changelog/latest.txt
  fm/nowplaying.gif
Labels: cute, type:redesign

#128 feat: display warning to users before upcoming release
  fm/bleh.css
  fm/bleh.user.css
  fm/bleh.user.js
  fm/changelog/img/violent.png
Labels: area:style

#127 feat: improve loading of stylesheet drastically
  fm/bleh.css
  fm/bleh.user.css
  fm/bleh.user.js
  fm/changelog/2025.0114.md
  fm/changelog/changelog.json
  fm/changelog/latest.txt
Labels: enhancement, area:style

#132 feat: anti-aircraft weekly But not weekly update
  fm/bleh.css
  fm/bleh.user.css
  fm/bleh.user.js
  fm/changelog/2025.0118.md
  fm/changelog/changelog.json
  fm/changelog/latest.txt
Labels: area:profiles, area:guest-features, area:artist, area:wiki, area:library

#133 feat: update
  fm/bleh.css
  fm/bleh.user.css
  fm/bleh.user.js
  fm/changelog/2025.0121.md
  fm/changelog/changelog.json
  fm/changelog/img/colours.png
  fm/changelog/img/sanitise.png
  fm/changelog/latest.txt
Labels: cute

#134 feat: new icons!!
  fm/bleh.css
  fm/bleh.user.css
  fm/bleh.user.js
  fm/changelog/2025.0124.md
  fm/changelog/2025.0125.md
  fm/changelog/changelog.json
  fm/changelog/latest.txt
Labels: cute

#136 fix: notifications that dont mention a user explicitly
  fm/bleh.user.js
Labels: system:badges, area:inbox
